image: gitpod/workspace-full-vnc

tasks:
  - command: |
      sudo apt-get remove -y firefox
      bash .devcontainer/installation.sh

ports:
  - port: 5900
    onOpen: ignore
  - port: 6080
    name: VNC Viewer
    onOpen: open-browser
